/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangelog_ implements Serializable {

    private static final long serialVersionUID = 1L;


    public Databasechangelog_() {}

    public Databasechangelog_(Databasechangelog_ value) {
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Databasechangelog_ (");


        sb.append(")");
        return sb.toString();
    }
}
