/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity.tables.pojos;



import java.util.List;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer employeeId;
    private String  fullName;
    private String  employeePosition;
    private String  companyBranch;
    private Integer manager;

    public Integer getTaskSumm() {
        return taskSumm;
    }

    public void setTaskSumm(Integer taskSumm) {
        this.taskSumm = taskSumm;
    }

    private Integer taskSumm;
    private List<Task> tasks;

    public List<Task> getTasks() {
        return tasks;
    }

    public void setTasks(List<Task> tasks) {
        this.tasks = tasks;
    }

    public Employee() {}

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Employee(Employee value) {
        this.employeeId = value.employeeId;
        this.fullName = value.fullName;
        this.employeePosition = value.employeePosition;
        this.companyBranch = value.companyBranch;
        this.manager = value.manager;
    }

    public Employee(
        Integer employeeId,
        String  fullName,
        String  employeePosition,
        String  companyBranch,
        Integer manager
    ) {
        this.employeeId = employeeId;
        this.fullName = fullName;
        this.employeePosition = employeePosition;
        this.companyBranch = companyBranch;
        this.manager = manager;
    }

    /**
     * Getter for <code>tasks.employee.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * Setter for <code>tasks.employee.employee_id</code>.
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * Getter for <code>tasks.employee.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>tasks.employee.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>tasks.employee.employee_position</code>.
     */
    public String getEmployeePosition() {
        return this.employeePosition;
    }

    /**
     * Setter for <code>tasks.employee.employee_position</code>.
     */
    public void setEmployeePosition(String employeePosition) {
        this.employeePosition = employeePosition;
    }

    /**
     * Getter for <code>tasks.employee.company_branch</code>.
     */
    public String getCompanyBranch() {
        return this.companyBranch;
    }

    /**
     * Setter for <code>tasks.employee.company_branch</code>.
     */
    public void setCompanyBranch(String companyBranch) {
        this.companyBranch = companyBranch;
    }

    /**
     * Getter for <code>tasks.employee.manager</code>.
     */
    public Integer getManager() {
        return this.manager;
    }

    /**
     * Setter for <code>tasks.employee.manager</code>.
     */
    public void setManager(Integer manager) {
        this.manager = manager;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(employeeId);
        sb.append(", ").append(fullName);
        sb.append(", ").append(employeePosition);
        sb.append(", ").append(companyBranch);
        sb.append(", ").append(manager);

        sb.append(")");
        return sb.toString();
    }
}
