/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity;


import com.sda.taskmanager.entity.tables.Employee;
import com.sda.taskmanager.entity.tables.Task;
import com.sda.taskmanager.entity.tables.records.EmployeeRecord;
import com.sda.taskmanager.entity.tables.records.TaskRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * tasks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployeeRecord> _EMPLOYEE_PK = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name(" employee_pk"), new TableField[] { Employee.EMPLOYEE.EMPLOYEE_ID }, true);
    public static final UniqueKey<TaskRecord> TASK_PK = Internal.createUniqueKey(Task.TASK, DSL.name("task_pk"), new TableField[] { Task.TASK.TASK_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmployeeRecord, EmployeeRecord> EMPLOYEE__MANAGER = Internal.createForeignKey(Employee.EMPLOYEE, DSL.name("manager"), new TableField[] { Employee.EMPLOYEE.MANAGER }, Keys._EMPLOYEE_PK, new TableField[] { Employee.EMPLOYEE.EMPLOYEE_ID }, true);
    public static final ForeignKey<TaskRecord, EmployeeRecord> TASK__TASK_PERFORMER = Internal.createForeignKey(Task.TASK, DSL.name("task_performer"), new TableField[] { Task.TASK.TASK_PERFORMER }, Keys._EMPLOYEE_PK, new TableField[] { Employee.EMPLOYEE.EMPLOYEE_ID }, true);
}
