/*
 * This file is generated by jOOQ.
 */
package entity;


import com.sda.taskmanager.entity.Tasks;
import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in tasks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>tasks. employee_employee_id_seq</code>
     */
    public static final Sequence<Integer> _EMPLOYEE_EMPLOYEE_ID_SEQ = Internal.createSequence(" employee_employee_id_seq", Tasks.TASKS, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>tasks.task_task_id_seq</code>
     */
    public static final Sequence<Integer> TASK_TASK_ID_SEQ = Internal.createSequence("task_task_id_seq", Tasks.TASKS, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
