/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity;


import com.sda.taskmanager.entity.tables.Databasechangelog_;
import com.sda.taskmanager.entity.tables.Employee;
import com.sda.taskmanager.entity.tables.Task;


/**
 * Convenience access to all tables in tasks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tasks.databasechangelog </code>.
     */
    public static final Databasechangelog_ DATABASECHANGELOG_ = Databasechangelog_.DATABASECHANGELOG_;

    /**
     * The table <code>tasks.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>tasks.task</code>.
     */
    public static final Task TASK = Task.TASK;
}
