/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity;


import com.sda.taskmanager.entity.tables.Databasechangelog_;
import com.sda.taskmanager.entity.tables.Employee;
import com.sda.taskmanager.entity.tables.Task;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tasks extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tasks</code>
     */
    public static final Tasks TASKS = new Tasks();

    /**
     * The table <code>tasks.databasechangelog </code>.
     */
    public final Databasechangelog_ DATABASECHANGELOG_ = Databasechangelog_.DATABASECHANGELOG_;

    /**
     * The table <code>tasks.employee</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>tasks.task</code>.
     */
    public final Task TASK = Task.TASK;

    /**
     * No further instances allowed
     */
    private Tasks() {
        super("tasks", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            entity.Sequences._EMPLOYEE_EMPLOYEE_ID_SEQ,
            entity.Sequences.TASK_TASK_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Databasechangelog_.DATABASECHANGELOG_,
            Employee.EMPLOYEE,
            Task.TASK);
    }
}
