/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity.tables.records;


import com.sda.taskmanager.entity.tables.Databasechangelog_;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangelog_Record extends TableRecordImpl<Databasechangelog_Record> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Databasechangelog_Record
     */
    public Databasechangelog_Record() {
        super(Databasechangelog_.DATABASECHANGELOG_);
    }
}
