/*
 * This file is generated by jOOQ.
 */
package com.sda.taskmanager.entity.tables.records;


import com.sda.taskmanager.entity.tables.Employee;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tasks.employee.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tasks.employee.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tasks.employee.full_name</code>.
     */
    public void setFullName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tasks.employee.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tasks.employee.employee_position</code>.
     */
    public void setEmployeePosition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tasks.employee.employee_position</code>.
     */
    public String getEmployeePosition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tasks.employee.company_branch</code>.
     */
    public void setCompanyBranch(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tasks.employee.company_branch</code>.
     */
    public String getCompanyBranch() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tasks.employee.manager</code>.
     */
    public void setManager(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>tasks.employee.manager</code>.
     */
    public Integer getManager() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Employee.EMPLOYEE.EMPLOYEE_ID;
    }

    @Override
    public Field<String> field2() {
        return Employee.EMPLOYEE.FULL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Employee.EMPLOYEE.EMPLOYEE_POSITION;
    }

    @Override
    public Field<String> field4() {
        return Employee.EMPLOYEE.COMPANY_BRANCH;
    }

    @Override
    public Field<Integer> field5() {
        return Employee.EMPLOYEE.MANAGER;
    }

    @Override
    public Integer component1() {
        return getEmployeeId();
    }

    @Override
    public String component2() {
        return getFullName();
    }

    @Override
    public String component3() {
        return getEmployeePosition();
    }

    @Override
    public String component4() {
        return getCompanyBranch();
    }

    @Override
    public Integer component5() {
        return getManager();
    }

    @Override
    public Integer value1() {
        return getEmployeeId();
    }

    @Override
    public String value2() {
        return getFullName();
    }

    @Override
    public String value3() {
        return getEmployeePosition();
    }

    @Override
    public String value4() {
        return getCompanyBranch();
    }

    @Override
    public Integer value5() {
        return getManager();
    }

    @Override
    public EmployeeRecord value1(Integer value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public EmployeeRecord value2(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public EmployeeRecord value3(String value) {
        setEmployeePosition(value);
        return this;
    }

    @Override
    public EmployeeRecord value4(String value) {
        setCompanyBranch(value);
        return this;
    }

    @Override
    public EmployeeRecord value5(Integer value) {
        setManager(value);
        return this;
    }

    @Override
    public EmployeeRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Integer employeeId, String fullName, String employeePosition, String companyBranch, Integer manager) {
        super(Employee.EMPLOYEE);

        setEmployeeId(employeeId);
        setFullName(fullName);
        setEmployeePosition(employeePosition);
        setCompanyBranch(companyBranch);
        setManager(manager);
    }
}
